swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Quint API

# Describe your paths here
paths:
  /users:
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `User` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfUsers
            type: array
            items:
              title: User
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
  /companies:
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Company` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfCompanies
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
definitions:
  User:
    type: object
    properties:
      id:
        type: number
      email:
        type: string
      password:
        type: string
      created_time:
        type: string
        description: Unix timestamp
  Student:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      major:
        type: string
      school:
        type: string
      resume_url:
        type: string
      linkedin_url:
        type: string
      photo_url:
        type: string
      headline:
        type: string
  Company:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      office_locations:
        type: array
        items:
          $ref: "#/definitions/OfficeLocation"
      job_posts:
        type: array
        items:
          $ref: "#/definitions/JobPost"
      industry:
        type: string
      website:
        type: string
      logo_url:
        type: string
      photos:
        type: string
      contact_person:
        $ref: "#/definitions/ContactPerson"
  OfficeLocation:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      address:
        type: string
      location_lat:
        type: number
      location_lon:
        type: number
  ContactPerson:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      role:
        type: string
      phone:
        type: string
      email:
        type: string
  JobPost:
    type: object
    properties:
      id:
        type: number
      role:
        type: string
      why_us:
        type: string
      salary:
        type: number
      technical_requirements:
        type: string
      internship_schedule:
        type: string
      tasks:
        type: string
      skills_gained:
        type: string
      experiences_gained:
        type: string
      contact_person:
        $ref: "#/definitions/ContactPerson"
  Application:
    type: object
    properties:
      id:
        type: number
      job_post:
        $ref: "#/definitions/JobPost"
      student:
        $ref: "#/definitions/Student"
      applied_at:
        type: string
        description: Unix timestamp
      status:
        type: string